### ISSUE TITLE
copy suggestions

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle.xyz#1]
_**Comments**_

- I think that the trustless section is vague. Trustless is already a loaded word, so if we want to focus on it more heavily as a part of the value proposition we should make it more specific. Govern is an even more loaded word and already has tons of negative connotation.

- local-first and connecting radicle to git is an attractive narrative. Makes it seem like another tool for what everyone uses right now - not just a completely new thing. 

- Secure and local-first as headlines are both very important, but the body content for both works really well together - combining them actually worked and could be a way to keep trustless as it's own section. 

_Suggested edits to discuss..._

**Peer-to-peer**
Extend git with peer-to-peer networking. No hassle to set up your own hosting, and no need to trust companies with your data.

**Local-first & secure**
Your issues, comments and reviews, are cryptographically signed and live on your machine. Everything is always available - even offline.

**Trustless**
Collectively manage your project assets, like access control and project ownership, with cryptographic multisigs and smart contracts.

**Sustainable**
Support your projects, contributors, and dependencies while releasing everything freely and openly. 

____________________________________

Other working drafts and iterations...

**Secure & trustless**
All your code artifacts are cryptographically signed and backed by secure peer identities. Program and extend access control with cryptographic multisigs and smart contracts. 

All your code artifacts are cryptographically signed and linked in a web of trust. Program and extend access control with cryptographic multisigs and smart contracts. 

**Peer-to-peer**
 No hassle to set up your own hosting, and no need to trust companies with your data.

**Secure**
All your artefacts—including code reviews—are cryptographically signed and backed by secure peer identities.

**Sustainable**
Support your projects, contributors, and dependencies while releasing free and open source.

**Comment by cloudhead** [comment]
@lftherios

**Comment by cloudhead** [comment]
> **Peer-to-peer**
> No hassle to set up your own hosting, and no need to trust companies with your data.

This shorter version works.

> **Local-first & secure**
> Your issues, comments and reviews, are cryptographically signed and live on your machine. Everything is always available - even offline.

I like the text, but I would change the heading to `Secure & offline`, or just `Secure`.

> **Trustless**
> Program access control, delegate project ownership, or collectively manage assets with cryptographic multisigs and smart contracts.
> 

The idea is good, but the formulation of the first two features needs work.

> **Sustainable**
> Support your projects, contributors, and dependencies while releasing everything freely and openly.
> 

I like parts of this, but not sure it makes sense - you have to support your own projects?

**Comment by cloudhead** [comment]
Another try.
---

**Peer-to-peer**
 No hassle setting up your own hosting, and no need to trust companies with your data.

**Secure**
Your issues, comments and reviews are cryptographically signed and live on your machine. Everything is always available -- even offline.

**Sustainable**
Support the projects you depend on and receive funding on your own terms, while releasing your work as free and open source software.

**Trustless*
Collectively manage assets with smart contracts, and delegate project ownership.

**Comment by abbey-titcomb** [comment]
@cloudhead @lftherios

Final Review! ✨🌱

Only thing changed is trustless sentence. Would we rather have identity or funds in the sentence

-----------------------------------------------------------------------------------

**Peer-to-peer**
No hassle to set up your own hosting, and no need to trust companies with your data.

**Secure**
Your issues, comments and reviews, are cryptographically signed and live on your machine. Everything is always available - even offline.

**Trustless**
Collectively manage your project assets —like access control, funds, and project ownership— with  multisignatures and smart contracts.

**Sustainable**
Support the projects you depend on and receive funding on your own terms, while releasing your work as free and open source.

**Comment by lftherios** [comment]
Looks good @abbey-titcomb 

One thing we could add is the following:

**Peer-to-peer**
No hassle to set up your own hosting, and no need to trust companies with your data. Radicle builds on git and extends it with a new networking layer.

**Comment by abbey-titcomb** [comment]
@cloudhead - what do you think?

**Comment by cloudhead** [comment]
**Peer-to-peer*
No hassle to set up your own hosting, and no need to trust companies with your data. Radicle builds on git and extends it with peer-to-peer replication and discovery.

**Comment by cloudhead** [comment]
Is access control an asset?

**Comment by abbey-titcomb** [comment]
I would say it's a project asset yes.

**Comment by lftherios** [comment]
> **Peer-to-peer**
> No hassle to set up your own hosting, and no need to trust companies with your data. Radicle builds on git and extends it with peer-to-peer replication and discovery.

works!

**Comment by cloudhead** [comment]
This is now live!
