### ISSUE TITLE
Update copy in “for the collective” section

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#104]
“Organize independent of platforms” or “form orgs and teams”

Confirm with Abbey what the final copy is here.

**Comment by juliendonck** [comment]
@abbey-titcomb you wanna weigh in here or are you gonna do a larger copy update?

**Comment by abbey-titcomb** [comment]
@juliendonck @brandonhaslegs — I'm definitely doing a larger copy update, let's keep this open but I'll revisit it when I push the changes from the feedback sessions
