### ISSUE TITLE
🧹 Clean up stuff

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#110]
- [ ] add `autocomplete="off"` to both email fields. showing autocomplete bugs the hell out of me. autocomplete is for long forms where you don't feel like entering your address or phone number or whatever. they can enter their damn email address one time without autocomplete. 🎸⚡️
- [ ] make the features headlines and bullet points left align
- [ ] make the links in the codelands section blue on hover, like the links in the protocols and roadmap sections.
- [ ]  increase the font-weight of everything that's set in Inter by 100 (it looks thinner than in the design… it's too delicate)

I think that's it.

**Comment by juliendonck** [comment]
Will do
