### ISSUE TITLE
Replace monadic.xyz with ` the radicle foundation`

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle.xyz#119]
mailto: hello@radicle.foundation

**Comment by brandonhaslegs** [comment]
Wonder if we can put up a quick text only site on radicle.foundation with a mailto link there. I hate hidden mailto links

**Comment by juliendonck** [comment]
We spoke about not having a website there, so maybe there's an other solution. 

We could do: Radicle is a project supported by the radicle foundation ([Email us](mailto:hello@radicle.foundation))
