### ISSUE TITLE
Update site title

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#129]
Right now it's just `radicle` but it should probably be something like `Radicle: A peer-to-peer stack for building software together.` or whatever the best text is

![image](https://user-images.githubusercontent.com/4406983/98916049-fb1e6900-24ca-11eb-8b8c-04299bf70fef.png)

Some sites just use the name. In that case, we should at least capitalize Radicle.

Some examples, if we want to write something:
`Urbit - Your personal server`
`Secure, Fast & Private Web Browser with Adblocker | Brave Browser`
`Cryptocurrency Tax Software | Crypto Tax | TokenTax`
`Coinbase – Buy & Sell Bitcoin, Ethereum, and more with trust`
`Status - Private, Secure Communication`

**Comment by abbey-titcomb** [comment]
You mean in the logo? Or in the tab bar?

**Comment by abbey-titcomb** [comment]
How about 

`Radicle - peer-to-peer code collaboration`

?
