### ISSUE TITLE
Update meta description

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#132]
Right now when you Google Radicle it just shows up with some text that cuts off. We should write something specific for this.

![image](https://user-images.githubusercontent.com/4406983/99518313-aed29d80-2990-11eb-922e-fba169daaf58.png)

**Comment by abbey-titcomb** [comment]
Is it just adding a `meta` tag?

**Comment by xla** [comment]
It's the [description](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-meta-element.html) variant a la:

`<meta name="description" content="..." />`
