### ISSUE TITLE
update section on Ethereum

### ISSUE THREAD

**Issue by lftherios** [radicle-dev/radicle.xyz#140]
current copy: "Harness the power of global identities and digital money. Fund and sustain your open source work without relying on intermediaries."

proposed copy: "Harness the power of decentralized organizations, community currencies and digital money. Fund and sustain your open source work without relying on intermediaries"

cc @juliendonck @abbey-titcomb

**Comment by abbey-titcomb** [comment]
"Harness the power of decentralized organizations, community currencies, and digital money. Fund and sustain your open-source work without relying on intermediaries."

@juliendonck

**Comment by juliendonck** [comment]
done
