### ISSUE TITLE
Email sign-up link is broken on mobile version of website

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle.xyz#149]
The `Email me a link` button on the mobile version of the website is an empty mailto: link.

We should have this link to the Mailchimp signup form -> http://eepurl.com/hhHxMX

![signal-2020-11-30-234924_002](https://user-images.githubusercontent.com/18275452/100679152-c7668e80-3366-11eb-963f-5126f53172a9.png)
![signal-2020-11-30-234924](https://user-images.githubusercontent.com/18275452/100679165-ccc3d900-3366-11eb-8916-dfeac75ab0f1.png)

**Comment by abbey-titcomb** [comment]
@cloudhead and I have realized this is a feature, not a bug. But the user behavior is still slightly confusing @brandonhaslegs @juliendonck — can we change the copy of the button to something like `remind yourself to download` or something?

**Comment by brandonhaslegs** [comment]
Yeah, I guess should say "Email yourself a link" Is it empty though? I wanted the subject and body to be filled in actually, so there is a problem here.

**Comment by cloudhead** [comment]
Yeah looks like it's empty on mobile, but works on desktop :thinking:

**Comment by abbey-titcomb** [comment]
Yeah, it's empty on mobile. Should we make a seperate issue for this @brandonhaslegs?

**Comment by SNikhill** [comment]
Greetings,
So, I tried your `mailto` button on my desktop and I got an **empty body** as well as an **empty subject**. 
- Email Client: Mozilla Thunderbird
- OS: Manjaro KDE

I believe this is what you guys want. (Yes, I did test it).
```html
<form
      action="mailto:?subject=Download the Radicle app&body=When you get back to your computer download the app here: www.radicle.xyz/downloads.html"
      method="POST"
      enctype="text/plain"
>
      <button id="email-me">Email me a link</button>
</form>
   ``` 

Kindly check it and if possible, can I make the desired changes in your code? 
(This will be one of my very few contributions to the open-source).

Regards
SNikhill
