### ISSUE TITLE
How to connect to the matrix server?

### ISSUE THREAD

**Issue by Powersource** [radicle-dev/radicle.xyz#150]
On the [website](https://radicle.xyz/) I can find this link https://matrix.radicle.community/ but that's just a link to your own instance of Element. How do I connect directly to your matrix from another instance of Element?

**Comment by Powersource** [comment]
Ah found this other page which helped https://docs.radicle.xyz/docs/understanding-radicle/faq#can-i-use-radicle-with-multiple-devices

**Comment by xla** [comment]
Thanks for reaching out @Powersource 

@abbey-titcomb You think this one is solved with radicle-dev/radicle-docs#83

**Comment by abbey-titcomb** [comment]
Yeah, looks like we need to surface our homeserver address more clearly. I added it to the docs with #83 — think we need it somewhere else @Powersource ?

**Comment by Powersource** [comment]
Maybe you could replace the link on https://radicle.xyz/ with https://matrix.to/#/#general:radicle.community ? I don't know how easy the docs are to find/navigate for new people
