### ISSUE TITLE
Timeline line on mobile doesn't reach the last dot

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#178]
![image](https://user-images.githubusercontent.com/4406983/107890797-17db9a00-6f1b-11eb-836e-63ab91ddc4db.png)

**Comment by SNikhill** [comment]
I shall like to take this task.

**Comment by SNikhill** [comment]
Question: Do you want it to reach the last dot or do you want it to reach till the end of the container. Basically, in PC mode, the line expands across the whole width similarly, in Phone it should expand across the whole height.

Are you okay with this?

**Comment by juliendonck** [comment]
> Question: Do you want it to reach the last dot or do you want it to reach till the end of the container. Basically, in PC mode, the line expands across the whole width similarly, in Phone it should expand across the whole height.
> 
> Are you okay with this?

I don't think it makes sense to have this run the whole height as it will cut through components below it. It works in the web view because it goes of the screen. For mobile i should probably just end in the dot.

**Comment by SNikhill** [comment]
Just wanted to show both the options. Kindly Pick one of them.
- Option One is just the height counter part of what we see on a normal computer screen
- Option Two is till the dot

### Option One
![LineOptionOne](https://user-images.githubusercontent.com/51415616/108053228-25a43300-7073-11eb-8e51-1ef12552ff9e.png)

### Option Two
![LineOptionTwo](https://user-images.githubusercontent.com/51415616/108053238-2937ba00-7073-11eb-862c-75bebf8f0c60.png)

**Comment by SNikhill** [comment]
In case anyone is wondering. `f2a9e5c` is the commit with the Line that just reaches the last dot.

**Comment by SNikhill** [comment]
@brandonhaslegs 
What do you think about Option 1?

**Comment by brandonhaslegs** [comment]
Well it does extend past the last dot on larger screens, so it would make sense. I just don't like how it just ends in the middle of nothing. I think overshooting the last dot would work if the gradient ended transparent like this. Then it also implies that the timeline continues further.
 
![image](https://user-images.githubusercontent.com/4406983/109282625-1153f900-781e-11eb-9d25-e343b577df81.png)

**Comment by brandonhaslegs** [comment]
Yeah let's go with that simple fading to transparent gradient above.

**Comment by SNikhill** [comment]
Okay.

**Comment by SNikhill** [comment]
Are you guys intentionally reversing the gradient? Like, down to top (on small screens) rather than top to bottom.

### Phone Screen
![image](https://user-images.githubusercontent.com/51415616/109290514-b1754680-784d-11eb-9094-f071ffc38440.png)

### Wide Screen
![image](https://user-images.githubusercontent.com/51415616/109290558-c3ef8000-784d-11eb-851f-3163bb5d0274.png)

The gradients are reversed for a small screen.

**Comment by brandonhaslegs** [comment]
Nope, not intentional. Gradient should be in the same direction on both small and large screens. Nice catch.
