### ISSUE TITLE
Path to styles `folder` is hardcoded

### ISSUE THREAD

**Issue by SNikhill** [radicle-dev/radicle.xyz#181]
# Description
**Path to the styles folder is hard coded.** 
This leads to style-sheet not found error when files which are siblings (Like, in the same folder as the directory `styles`) of the styles directory are opened up in a browser.

## Proof
![image](https://user-images.githubusercontent.com/51415616/107935331-42733480-6fa7-11eb-831c-169ca4257c12.png)

- **Browser Used:** Mozilla Firefox Developer Edition

**Comment by juliendonck** [comment]
Hey, thanks for opening the issue. I'm unclear what you're suggesting here. Since this is a static html and css website how else would we do it?

**Comment by juliendonck** [comment]
Figured it out.

**Comment by SNikhill** [comment]
Okay, you removed the relative paths. :)

**Comment by SNikhill** [comment]
@juliendonck 
Sorry for the tag.
But, may I know exactly how do you run this project on your PC?
I am getting a feeling that I am doing something wrong.
