### ISSUE TITLE
Blog feedback issue

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle.xyz#182]
Now that the blog is live and doesn't have any more bugs, I thought it'd be a good time to collect all the feedback and do a last pass.

Here's some feedback that we had already collected:
by @cloudhead:
- I find the title sizes a too big, makes it hard to navigate that page -- I can't imagine there being more than 3 posts on there, as it'll require a lot of scrolling.

by @abbey-titcomb:
- The Druk text works, unless the title is too long, then it kind of stacks weird. Maybe we change the header text in the blog post to be something more normie? Or make it take up less lines?

**Comment by cloudhead** [comment]
> I find the title sizes a too big, makes it hard to navigate that page -- I can't imagine there being more than 3 posts on there, as it'll require a lot of scrolling.

This looks fixed!

My only other feedback is that the list items have the numbers/bullets outside of the text width, which looks quite weird.
