### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle.xyz#2]
@juliendonck asked me to take a (fresh) look at the new radicle.xyz. I am listing my findings/suggestions here.

- The "Sustainable" section is the only section with text in italic. Not a major issue, but I didn't understand why this part was especially emphasized and others not.
- The old/new collaboration model part was a bit confusing. First I thought "Radicle was built..." is referencing the first version of Radicle, so I expected a run down of what has changed or why. Without making this connection, the start makes it sound like Radicle is already finished and I would be able to use it/play around with it.
- There is no explanation on the page about what I will find if I follow the `code` link, ie why there are so many different projects and how they interact.

**Comment by abbey-titcomb** [comment]
@MeBrei thanks for the feedback

_- The "Sustainable" section is the only section with text in italic. Not a major issue, but I didn't understand why this part was especially emphasized and others not._

Yeah, I didn't realize that. Isn't consistent with the rest so we should probably change that.

- The old/new collaboration model part was a bit confusing. First I thought "Radicle was built..." is referencing the first version of Radicle, so I expected a run down of what has changed or why. Without making this connection, the start makes it sound like Radicle is already finished and I would be able to use it/play around with it.

Hm. This is a good point. The website is going to be paired with a blog post that dives more into "what's changed" (see draft [here](https://www.notion.so/monadic/v2-206f9411255349128776872c12012aec)). I wonder if we should change the language in this section or at link to the blog post? 

- There is no explanation on the page about what I will find if I follow the code link, ie why there are so many different projects and how they interact.

Great point. I agree, just not sure if we can avoid this at this point in time......I think the goal of this website is to keep building on it continuously - adding new content and references etc... One of those will be a more comprehensive overview of the stack once we have more defined technical specs from different teams. So maybe a more comprehensive readme is necessary with the launch..

@cloudhead - what are your thoughts on above?

**Comment by cloudhead** [comment]
> @juliendonck asked me to take a (fresh) look at the new radicle.xyz. I am listing my findings/suggestions here.
> 
> * The "Sustainable" section is the only section with text in italic. Not a major issue, but I didn't understand why this part was especially emphasized and others not.

Another way to achieve the effect of emphasis would be to add punctuation, eg. "receive funding---on your own terms."

> * The old/new collaboration model part was a bit confusing. First I thought "Radicle was built..." is referencing the first version of Radicle, so I expected a run down of what has changed or why. Without making this connection, the start makes it sound like Radicle is already finished and I would be able to use it/play around with it.

Maybe we could say "is being built" :thinking: 

> * There is no explanation on the page about what I will find if I follow the `code` link, ie why there are so many different projects and how they interact.

That I think is fine for the moment, though indeed having better READMEs might be nice.

**Comment by cloudhead** [comment]
Addressed here: b99f48c
