### ISSUE TITLE
Update the main CTA at the top to link to the downloads page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#224]
The way to sign up for the newsletter will remain in the footer.

**Comment by SNikhill** [comment]
Greetings @brandonhaslegs 

I believe, by Main CTA, you meant the 'Try It' button. It is already linked to the Downloads Page but, the arrow next to it suggests that it takes the user to the Footer.

![image](https://user-images.githubusercontent.com/51415616/114513350-b8b6af00-9c57-11eb-9c2c-35d8aa445f10.png)

I shall replace the Downwards arrow with the Tilted one.

**Comment by brandonhaslegs** [comment]
Actually just want to get rid of the email newsletter sign up in the black bar and replace it with a with a download button. I'll take care of it. Thanks for the enthusiasm though @SNikhill!
