### ISSUE TITLE
Add a Community page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#236]
Since we have many places where our community exists, I thought we could add a page to the website that serves as a sort of general-purpose place to understand what we use each place for.

This page would link to these places:
- [Discourse](radicle.community)
- [Discord](https://discord.gg/xEGT4vdH)
- [Matrix](matrix.radicle.community)
- [Twitter](twitter.com/radicle)
- [Telegram](telegram.me/radicleworld)
- [Telegram (Thailand)](https://t.me/radicleThailand)

Start of the Figma design [here](https://www.figma.com/file/mM35Q1jG2cADW5ZWYyBIMb/Radicle-Website?node-id=1861%3A84705).

![image](https://user-images.githubusercontent.com/4406983/118837323-f943c100-b8c4-11eb-8aca-e2fc7db5425f.png)

**Comment by SNikhill** [comment]
Greetings @brandonhaslegs 

I had a question regarding the `design` label.

Is there a way that outside contributors could also "pitch-in" on the development of the page and design?

**Comment by brandonhaslegs** [comment]
Hey @SNikhill for sure! Right now @abbey-titcomb is working on some content for the page, but after that anyone can suggest a design for this page. And more globally across all of our repos, issues marked with the `design` label (for example in [the Radicle Upstream repo](https://github.com/radicle-dev/radicle-upstream/issues?q=is%3Aopen+is%3Aissue+label%3Adesign)) can be tackled by anyone.

If you want to work in design software first, all the design files are publicly available. Here's the [design for the marketing website](https://www.figma.com/file/mM35Q1jG2cADW5ZWYyBIMb/Radicle-Website?node-id=1861%3A84705), and here's the [design file for Radicle Upstream](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=4147%3A7246). You won't be able to edit them, but you can make a copy and work on something, and just post the idea in the corresponding issue.

**Comment by SNikhill** [comment]
Thank you for informing me @brandonhaslegs  :)

Have a great day ahead.
