### ISSUE TITLE
"Try it" current nav state

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#239]
The nav item disappears when you're on that page. 

- [ ] Add "Try it" back into the nav with an active state when you're on that page

![image](https://user-images.githubusercontent.com/4406983/119651766-9eaae780-be25-11eb-8fd1-e9a3dd72f805.png)

**Comment by SNikhill** [comment]
I shall like to take this one.

**Comment by SNikhill** [comment]
I followed what Community Page had done.

I do feel that there should be a better method to handle the same like, passing an active variable to `header` partial rather than duplicating the whole header.
