### ISSUE TITLE
Link the community block to the community page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#246]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/4406983/122369443-7ca51080-cf5e-11eb-91d1-babd16bfc318.png">

Text should change from "Join our community or chat with us" to just "[Hang out with us](https://radicle.xyz/community.html)"

**Comment by soham4abc** [comment]
I can work on this if possible pls assign
