### ISSUE TITLE
Update Discord link on Community page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#268]
On this page https://radicle.xyz/community.html the Discord link should be changed to https://discord.com/channels/841318878125490186/843873418205331506

**Comment by PuneetDabral** [comment]
sir can i ....?

**Comment by brandonhaslegs** [comment]
@PuneetDabral Yes go for it! Let me know if you need anything.

**Comment by PuneetDabral** [comment]
sir check my pr...now its ok..so i can motivate my self ....!!
