### ISSUE TITLE
Live site has outdated download links

### ISSUE THREAD

**Issue by Jayman2000** [radicle-dev/radicle.xyz#284]
[The “Try it” page on the live site](https://radicle.xyz/tryit.html) has download links for Radicle Upstream 0.2.11. [The latest version is 0.2.13.](https://github.com/radicle-dev/radicle-upstream/blob/main/CHANGELOG.md#0213-2021-12-17) When I build the site from source, the “Try it” page links to the latest version.

**Comment by brandonhaslegs** [comment]
@rudolfs wha happen

**Comment by Jayman2000** [comment]
I just checked the live site again, and it looks like the problem was fixed.

**Comment by rudolfs** [comment]
Good catch @Jayman2000!

It looks like it was rolled back by accident in:
https://github.com/radicle-dev/radicle.xyz/pull/277/files#diff-4000ffdff4775a35f927a300050e4cbcda6a9a7e87e0076d3c46e3b89f9b4533R50

What most likely happened is that @brandonhaslegs forgot to pull in the latest changes before working on the website and it also slipped through code review.

Maybe we need a more robust way of linking the downloads? One way to prevent this would be to embed a bit of javascript in the download page that pulls the latest version from https://releases.radicle.xyz/latest.json and sets it for the download button. This way we wouldn't need to update the website manually anymore.

What do you think @geigerzaehler?

**Comment by brandonhaslegs** [comment]
Oopsies

**Comment by geigerzaehler** [comment]
> Maybe we need a more robust way of linking the downloads? One way to prevent this would be to embed a bit of javascript in the download page that pulls the latest version from https://releases.radicle.xyz/latest.json and sets it for the download button. This way we wouldn't need to update the website manually anymore.

Alternatively, we could just publish the latest release as `https://releases.radicle.xyz/radicle-upstream.AppImage` omitting the version. Is it necessary to include the version in the filename?

**Comment by rudolfs** [comment]
Hm, that could work too. But I'd rather keep the version in the filename, it's much easier to check what got downloaded without installing it.

**Comment by Jayman2000** [comment]
> Is it necessary to include the version in the filename?

I wouldn’t say that it’s necessary, but it’s useful. When I use software that doesn’t have managed updates (software that doesn’t auto-update and isn’t updated by a package manager), I’ll periodically go to its download page to see if any updates are available. Having the version number in the filename helps in two ways:
1. I can look at the filename on my computer to figure out what version I currently have. I can also do this from Upstream itself, but it’s probably slower to do it that way.
2. I can look at the filename on the download page to figure out what the latest version is. At the moment, this is the only thing on the download page that tells me what the latest version is.

**Comment by geigerzaehler** [comment]
Thanks for the input. I think it makes sense to keep it as is and not change the file name.

I’m not opposed to having some JavaScript fetch the latest version to determine the URL. But I also don’t think it’s quite worth our time to implement and maintain this.
