### ISSUE TITLE
A list of things we could fix now

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle.xyz#299]
As we wait on a full radicle.xyz redesign, here are a couple suggestions for fixes we could make in the meantime:

- [x] Link `Blog` header to radicle.mirror.xyz 
- [x] Replace `matrix.radicle.community` link on Community page with `https://matrix.to/#/#radicle-space:matrix.org`
- [x] Add link to `radicle.network` to Try It page (Under Web)

Will add more here as they come.

**Comment by brandonhaslegs** [comment]
Fixed the things for me, broke out others to separate issues.

**Comment by brandonhaslegs** [comment]
Closing this for now because I fixed these and broke out the others into separate issues
