### ISSUE TITLE
Add www to the SSL certificate scope

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle.xyz#35]
Now `www.radicle.xyz` does redirect to `https:://radicle.xyz`. However, `https://www.radicle.xyz` fails with a `NET::ERR_CERT_COMMON_NAME_INVALID` error, as the domain's certificate, doesn't include the `www` subdomain.

We need to generate a new certificate including it and apply it. I can't do this since I don't have permissions to access that dashboard on google cloud.

@cloudhead can you do it or give me permissions to?

**Comment by cloudhead** [comment]
Hmm for some reason I thought these certs were managed by GitHub. I'll give you access to gcloud so you can find out.

**Comment by cloudhead** [comment]
Looks like you already have admin rights over DNS resources. Can you check? It's under Cloud DNS.

**Comment by NunoAlexandre** [comment]
Hm, under the [`Network Services`](https://console.cloud.google.com/net-services/dns/zones/radicle?project=opensourcecoin&authuser=1&folder&organizationId&supportedpurview=project&dnsResourceRecordSetssize=50) I can only access `Cloud DNS`, where I think I need to access `Load Balancing`.

**Comment by cloudhead** [comment]
You should have access to everything now.

**Comment by NunoAlexandre** [comment]
Looks like! Thanks. I will follow up on this.

**Comment by brandonhaslegs** [comment]
@NunoAlexandre Maybe we can fix this before we launch the new site?

**Comment by NunoAlexandre** [comment]
> @NunoAlexandre Maybe we can fix this before we launch the new site?

Yes. When is the release?

**Comment by brandonhaslegs** [comment]
@NunoAlexandre This week I guess! (Probably next week.)

**Comment by NunoAlexandre** [comment]
I have tried to set this up last week or two weeks ago on GCP with no success. @cloudhead also didn't know further, unfortunately.

My take is that we can live well as things are now, as only the very specific link [https://www.radicle.xyz](https://www.radicle.xyz) won't work. No one will be typing `https://www.` though.  [https://radicle.xyz](https://radicle.xyz) and  [http://www.radicle.xyz](http://www.radicle.xyz) work well and lead the user to an https-secured state.

**Comment by brandonhaslegs** [comment]
Before I started working at Monadic I did type it in. When I saw that it was messed up, I thought that was weird. To me it feels like a lack of attention to detail.

**Comment by xla** [comment]
> Before I started working at Monadic I did type it in. When I saw that it was messed up, I thought that was weird. To me it feels like a lack of attention to detail.

It's possible to address issue, @NunoAlexandre and I have talked about a path forward, which involves moving away form hosting on github pages. If we see this being important enough we can outline the steps necessary to migrate.
