### ISSUE TITLE
rad: 'patch' is not a rad command

### ISSUE THREAD

**Issue by Gozala** [radicle-dev/radicle.xyz#60]
```
rad patch propose 56d6a0e
rad: 'patch' is not a rad command. See 'rad help' for a list of available commands.
➜  radicle-garden (my-garden) rad --help  
usage: rad <command> [<args>]

Available commands:
   daemon-ipfs
   daemon-radicle
   diff
   help
   ipfs
   issue
   key
   machines
   project
   replicate
   version
rad version  
radicle version 0.0.0
```

**Comment by jkarni** [comment]
Looks like this is the same brew-is-using-an-old-version issue, I think. Can you try:

```
brew uninstall radicle-alpha
brew update 
brew install radicle-alpha
brew link --overwrite radicle-alpha
brew service restart radicle-alpha
```
(I think that's right - I don't have a mac.)

**Comment by Gozala** [comment]
Alright reinstall seemed to have gotten the right version, and all seems to work now. However `rad version` still reports `0.0.0` not sure if that's expected

```
rad version
radicle version 0.0.0
readlink $(which rad)
../Cellar/radicle-alpha/0.1.0/bin/rad
```

So I think I have `0.1.0` now.

**Comment by xla** [comment]
@Gozala Thanks for raisng the issue and taking the time resolving it, we will look into the wrongly reported version number. Will close this one for now as it seems addressed.
