### ISSUE TITLE
Please use HTTPS

### ISSUE THREAD

**Issue by Gozala** [radicle-dev/radicle.xyz#62]
At the moment if you visit https://www.radicle.xyz/ this is what you'll see (because certificate is issued isn't for  radicle.xyz)

<img width="1007" alt="Screen Shot 2019-03-12 at 12 15 46 PM" src="https://user-images.githubusercontent.com/21236/54229012-a12cfb00-44c0-11e9-9c83-68b99e356b66.png">

**Comment by xla** [comment]
Thanks for raising awareness, it seems cert propagation took a while and we should now be safely servince https://radicle.xyz/

Please reopen if you still run into trouble.
