### ISSUE TITLE
RSS / Atom

### ISSUE THREAD

**Issue by hxrts** [radicle-dev/radicle.xyz#7]
This would definitely be a nice-to-have. RSS definitely declining in popularity, but it's one of the early open web standards and anyone that does subscribe to our RSS establishes a direct broadcast channel with us.

**Comment by onurakpolat** [comment]
We have it: http://radicle.xyz/blog/index.xml

**Comment by xla** [comment]
Can we cloes?

**Comment by hxrts** [comment]
oh perfect. thanks! closing.
