### ISSUE TITLE
animateDivider function wastes too much CPU

### ISSUE THREAD

**Issue by duobei** [radicle-dev/radicle.xyz#70]
The animateDivider function wastes too much CPU in the page http://radicle.xyz .

**Comment by coolmedium** [comment]
I was just about to open an issue about the same thing.  Its a neat effect, but it should be a little more conscientious of users' battery life.  Looking at project documentation should not throttle my CPU.

**Comment by juliendonck** [comment]
Thank you for raising the issue. We agree that it's not a good user experience. I'll take a look into it.

**Comment by juliendonck** [comment]
We've taking the animation out on the docs page to lighten the load while browsing the docs (see #77). 

We're still looking into improving the animating divider in other places, so I'll leave the issue open.
