### ISSUE TITLE
www.radicle.xyz doesn't redirect to radicle.xyz

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle.xyz#8]
:(

<img width="1660" alt="Screenshot 2020-01-20 at 14 01 03" src="https://user-images.githubusercontent.com/2326909/72728282-4d357d00-3b8d-11ea-85e8-97b079d486bb.png">

**Comment by juliendonck** [comment]
@NunoAlexandre here's an issue for it if you want to track it in your work :)

**Comment by NunoAlexandre** [comment]
Now `www.radicle.xyz` does redirect to `https:://radicle.xyz`. However, `https://www.radicle.xyz` fails with a `NET::ERR_CERT_COMMON_NAME_INVALID` error, as the domain's certificate, doesn't include the `www` subdomain. Will create an issue for that.
