### ISSUE TITLE
Fix horizontal overflow

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#80]
Can't figure out what's causing the horizontal overflow. Might be the timeline line in the timeline section.

**Comment by juliendonck** [comment]
is this on mobile?

**Comment by brandonhaslegs** [comment]
It only shows up when I have the inspector tools open in chrome… can't reproduce in firefox. 🤔 Need to test on a real mobile device because weird things like this sometimes happen.

**Comment by juliendonck** [comment]
yeah agreed
